FROM node:24.6.0-alpine

# Crear directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar TODAS las dependencias, incluyendo devDependencies para testing
RUN npm ci

# Copiar el código fuente (aunque será sobreescrito por el volumen en modo dev)
COPY . .

# Crear usuario no root para seguridad
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001

# Cambiar ownership de los archivos
RUN chown -R nodejs:nodejs /app
USER nodejs

# Exponer el puerto
EXPOSE 3000

# El comando por defecto. Será sobreescrito en docker-compose.dev.yml
CMD ["node", "app.js"]