FROM node:24.6.0-alpine

# Instalar dependencias necesarias para el script de espera
RUN apk add --no-cache bash

# Crear directorio de trabajo
WORKDIR /app

# Descargar y hacer ejecutable el script wait-for
ADD https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for /usr/local/bin/wait-for
RUN chmod +x /usr/local/bin/wait-for

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar TODAS las dependencias, incluyendo devDependencies para testing
RUN npm ci

# Copiar el código fuente (aunque será sobreescrito por el volumen en modo dev)
COPY . .

# Crear usuario no root para seguridad
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001

# Cambiar ownership de los archivos Y DEL SCRIPT
RUN chown -R nodejs:nodejs /app
RUN chown nodejs:nodejs /usr/local/bin/wait-for

USER nodejs

# Exponer el puerto
EXPOSE 3000

# El comando por defecto. Será sobreescrito en docker-compose.dev.yml
CMD ["node", "app.js"]