services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/usr/local/bin/wait-for", "postgres:5432", "--", "npm", "test"]
    # Load all variables from the .env file
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    restart: "no"

  postgres:
    image: postgres:15-alpine
    # Load all variables from the .env file
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $DB_NAME_TEST"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:

networks:
  app-network:
    driver: bridge